In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("data/sales.csv")

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [7]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [8]:
df.isna()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False
9996,False,True,False,True,False,False,True,False
9997,False,False,False,False,False,False,True,False
9998,False,False,False,True,False,False,True,False
9999,False,False,False,False,False,False,False,False

In [11]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [14]:
df.isna().sum().sum()

np.int64(6826)

In [15]:
df.dropna(inplace = True)

In [16]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [17]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [19]:
df.drop_duplicates(inplace = True)

1 Removing values. 2 changing data types.

In [24]:
pd.Series(df["Transaction ID"].unique().tolist()).str.startswith("TXN").value_counts()

True    4550
Name: count, dtype: int64

In [26]:
df["Item"].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad',  'UNKNOWN', 'Sandwich',
    'Juice', 'Smoothie',    'ERROR',      'Tea']
Length: 10, dtype: str

In [27]:
df["Quantity"].unique()

<StringArray>
['2', '4', '3', '5', 'ERROR', '1', 'UNKNOWN']
Length: 7, dtype: str

In [30]:
def unique_values(df):
    for column in df.columns:
        print(f"\nColumn: {column}")
        print(df[column].unique())

unique_values(df)

Column: Transaction ID
<StringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_4433211', 'TXN_6699534', 'TXN_2548360', 'TXN_3051279', 'TXN_7619095',
 ...
 'TXN_3124078', 'TXN_8076061', 'TXN_9668108', 'TXN_5548914', 'TXN_9933628',
 'TXN_3142496', 'TXN_2858441', 'TXN_3897619', 'TXN_2739140', 'TXN_6170729']
Length: 4550, dtype: str

Column: Item
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad',  'UNKNOWN', 'Sandwich',
    'Juice', 'Smoothie',    'ERROR',      'Tea']
Length: 10, dtype: str

Column: Quantity
<StringArray>
['2', '4', '3', '5', 'ERROR', '1', 'UNKNOWN']
Length: 7, dtype: str

Column: Price Per Unit
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', 'UNKNOWN', 'ERROR']
Length: 8, dtype: str

Column: Total Spent
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',     '9.0',    '16.0',    '25.0',
     '8.0',    '15.0',     '6.0',    '20.0',     '5.0',     '2.0',     '3.0',
     '1.0', 'UNKNOWN',     '7.5',     '4.5',     '1.5']
Length: 19, dtype: str

Column: Payment Method
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR']
Length: 5, dtype: str

Column: Location
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', 'ERROR']
Length: 4, dtype: str

Column: Transaction Date
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-10-06', '2023-10-28', '2023-11-07',      'ERROR', '2023-05-03',
 ...
 '2023-11-11', '2023-05-20', '2023-08-08', '2023-01-23', '2023-02-14',
 '2023-11-14', '2023-05-22', '2023-09-24', '2023-05-25', '2023-05-13']
Length: 367, dtype: str

In [32]:
df = df[~df.isin(["UNKNOWN", "ERROR"]).any(axis=1)]

In [33]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [35]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [36]:
df["Quantity"]= df["Quantity"].astype(int)

In [37]:
df.dtypes

Transaction ID        str
Item                  str
Quantity            int64
Price Per Unit        str
Total Spent           str
Payment Method        str
Location              str
Transaction Date      str
dtype: object

In [38]:
df["Price Per Unit"]= df["Price Per Unit"].astype(float)
df["Total Spent"]= df["Total Spent"].astype(float)

In [41]:
df.dtypes

Transaction ID                 str
Item                           str
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [40]:
df["Transaction Date"]= pd.to_datetime(df["Transaction Date"])

In [43]:
df = df.sort_values("Transaction ID").reset_index(drop = True)

In [44]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1000555,Tea,1,1.5,1.5,Credit Card,In-store,2023-10-19
1,TXN_1002457,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-09-29
2,TXN_1004184,Smoothie,1,4.0,4.0,Credit Card,In-store,2023-05-18
3,TXN_1004563,Tea,5,1.5,7.5,Credit Card,In-store,2023-10-28
4,TXN_1005331,Coffee,1,2.0,2.0,Digital Wallet,Takeaway,2023-11-04
...,...,...,...,...,...,...,...,...
3084,TXN_9989719,Smoothie,2,4.0,8.0,Credit Card,Takeaway,2023-11-26
3085,TXN_9991225,Cake,5,3.0,15.0,Credit Card,Takeaway,2023-02-03
3086,TXN_9992148,Tea,3,1.5,4.5,Cash,Takeaway,2023-01-14
3087,TXN_9996195,Juice,5,3.0,15.0,Digital Wallet,In-store,2023-03-16
3088,TXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27

In [45]:
df.to_csv("data/sales_cleaned.csv")